### ISSUE TITLE
Gráfico/Insight5 - Segmentação de Usuários

### ISSUE THREAD

**Issue by Samuel-Silv** [Samuel-Silv/SmartPhoneUsage#8]
Identificar "heavy users" (com mais de 5 horas de uso diário) e "light users".

**Comment by bidobido** [comment]
Total_App_Usage_Hours   User_Type
0                   2.61  Light User
1                   2.13  Light User
2                   7.28  Heavy User
3                   1.20  Light User
4                   6.31  Heavy User
User_Type
Heavy User    631
Light User    369
